fs: f2fs: Fix macro signature usage on F2FS_RW_ATTR_640 and F2FS_RO_ATTR
After android12-5.10-lts 5.10.251 F2FS_ATTR_OFFSET now requires a new argument `_size`.

../fs/f2fs/sysfs.c:1178:1: error: too few arguments provided to function-like macro invocation
 1178 | F2FS_RO_ATTR(GC_THREAD, f2fs_gc_kthread, gc_urgent_sleep_time,
      | ^
../fs/f2fs/sysfs.c:1164:39: note: expanded from macro 'F2FS_RO_ATTR'
 1164 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1140:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1140 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size) \
      |         ^
../fs/f2fs/sysfs.c:1178:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1178 | F2FS_RO_ATTR(GC_THREAD, f2fs_gc_kthread, gc_urgent_sleep_time,
      | ^
      | int
../fs/f2fs/sysfs.c:1162:2: note: expanded from macro 'F2FS_RO_ATTR'
 1162 |         F2FS_ATTR_OFFSET(struct_type, name, 0444,               \
      |         ^
../fs/f2fs/sysfs.c:1221:1: error: too few arguments provided to function-like macro invocation
 1221 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_gc_stat, sec_stat);
      | ^
../fs/f2fs/sysfs.c:1159:39: note: expanded from macro 'F2FS_RW_ATTR_640'
 1159 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1140:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1140 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size) \
      |         ^
../fs/f2fs/sysfs.c:1221:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1221 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_gc_stat, sec_stat);
      | ^
      | int
../fs/f2fs/sysfs.c:1157:2: note: expanded from macro 'F2FS_RW_ATTR_640'
 1157 |         F2FS_ATTR_OFFSET(struct_type, name, 0640,               \
      |         ^
../fs/f2fs/sysfs.c:1222:1: error: too few arguments provided to function-like macro invocation
 1222 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_io_stat, sec_stat);
      | ^
../fs/f2fs/sysfs.c:1159:39: note: expanded from macro 'F2FS_RW_ATTR_640'
 1159 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1140:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1140 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size) \
      |         ^
../fs/f2fs/sysfs.c:1222:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1222 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_io_stat, sec_stat);
      | ^
      | int
../fs/f2fs/sysfs.c:1157:2: note: expanded from macro 'F2FS_RW_ATTR_640'
 1157 |         F2FS_ATTR_OFFSET(struct_type, name, 0640,               \
      |         ^
../fs/f2fs/sysfs.c:1223:1: error: too few arguments provided to function-like macro invocation
 1223 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_fsck_stat, sec_fsck_stat);
      | ^
../fs/f2fs/sysfs.c:1159:39: note: expanded from macro 'F2FS_RW_ATTR_640'
 1159 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1140:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1140 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size) \
      |         ^
../fs/f2fs/sysfs.c:1223:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1223 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_fsck_stat, sec_fsck_stat);
      | ^
      | int
../fs/f2fs/sysfs.c:1157:2: note: expanded from macro 'F2FS_RW_ATTR_640'
 1157 |         F2FS_ATTR_OFFSET(struct_type, name, 0640,               \
      |         ^
../fs/f2fs/sysfs.c:1231:1: error: too few arguments provided to function-like macro invocation
 1231 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_defrag_stat, s_sec_part_best_extents);
      | ^
../fs/f2fs/sysfs.c:1159:39: note: expanded from macro 'F2FS_RW_ATTR_640'
 1159 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1140:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1140 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size) \
      |         ^
../fs/f2fs/sysfs.c:1231:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1231 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_defrag_stat, s_sec_part_best_extents);
      | ^
      | int
../fs/f2fs/sysfs.c:1157:2: note: expanded from macro 'F2FS_RW_ATTR_640'
 1157 |         F2FS_ATTR_OFFSET(struct_type, name, 0640,               \
      |         ^
  CC [M]  drivers/soc/samsung/cpif/modem_main.o
  CC      lib/oid_registry.o
../fs/f2fs/sysfs.c:1323:2: error: use of undeclared identifier 'f2fs_attr_gc_urgent_sleep_time'; did you mean 'f2fs_attr_gc_min_sleep_time'?
 1323 |         ATTR_LIST(gc_urgent_sleep_time),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1321:27: note: expanded from macro 'ATTR_LIST'
 1321 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:149:1: note: expanded from here
  149 | f2fs_attr_gc_urgent_sleep_time
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1180:1: note: 'f2fs_attr_gc_min_sleep_time' declared here
 1180 | F2FS_RW_ATTR(GC_THREAD, f2fs_gc_kthread, gc_min_sleep_time, min_sleep_time);
      | ^
../fs/f2fs/sysfs.c:1151:2: note: expanded from macro 'F2FS_RW_ATTR'
 1151 |         F2FS_ATTR_OFFSET(struct_type, name, 0644,               \
      |         ^
../fs/f2fs/sysfs.c:1141:25: note: expanded from macro 'F2FS_ATTR_OFFSET'
 1141 | static struct f2fs_attr f2fs_attr_##_name = {                   \
      |                         ^
<scratch space>:133:1: note: expanded from here
  133 | f2fs_attr_gc_min_sleep_time
      | ^
../fs/f2fs/sysfs.c:1365:2: error: use of undeclared identifier 'f2fs_attr_sec_gc_stat'; did you mean 'f2fs_attr_sec_fs_stat'?
 1365 |         ATTR_LIST(sec_gc_stat),
      |         ^~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1321:27: note: expanded from macro 'ATTR_LIST'
 1321 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:13:1: note: expanded from here
   13 | f2fs_attr_sec_gc_stat
      | ^~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1246:1: note: 'f2fs_attr_sec_fs_stat' declared here
 1246 | F2FS_GENERAL_RO_ATTR(sec_fs_stat);
      | ^
../fs/f2fs/sysfs.c:1167:25: note: expanded from macro 'F2FS_GENERAL_RO_ATTR'
 1167 | static struct f2fs_attr f2fs_attr_##name = __ATTR(name, 0444, name##_show, NULL)
      |                         ^
<scratch space>:40:1: note: expanded from here
   40 | f2fs_attr_sec_fs_stat
      | ^
  CC [M]  drivers/soc/samsung/gnssif/gnss_main.o
../fs/f2fs/sysfs.c:1366:2: error: use of undeclared identifier 'f2fs_attr_sec_io_stat'; did you mean 'f2fs_attr_sec_fs_stat'?
 1366 |         ATTR_LIST(sec_io_stat),
      |         ^~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1321:27: note: expanded from macro 'ATTR_LIST'
 1321 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:14:1: note: expanded from here
   14 | f2fs_attr_sec_io_stat
      | ^~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1246:1: note: 'f2fs_attr_sec_fs_stat' declared here
 1246 | F2FS_GENERAL_RO_ATTR(sec_fs_stat);
      | ^
../fs/f2fs/sysfs.c:1167:25: note: expanded from macro 'F2FS_GENERAL_RO_ATTR'
 1167 | static struct f2fs_attr f2fs_attr_##name = __ATTR(name, 0444, name##_show, NULL)
      |                         ^
<scratch space>:40:1: note: expanded from here
   40 | f2fs_attr_sec_fs_stat
      | ^
  CC      net/ipv4/tcp_minisocks.o
../fs/f2fs/sysfs.c:1367:2: error: use of undeclared identifier 'f2fs_attr_sec_fsck_stat'; did you mean 'f2fs_attr_sec_fs_stat'?
 1367 |         ATTR_LIST(sec_fsck_stat),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1321:27: note: expanded from macro 'ATTR_LIST'
 1321 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:15:1: note: expanded from here
   15 | f2fs_attr_sec_fsck_stat
      | ^~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1246:1: note: 'f2fs_attr_sec_fs_stat' declared here
 1246 | F2FS_GENERAL_RO_ATTR(sec_fs_stat);
      | ^
../fs/f2fs/sysfs.c:1167:25: note: expanded from macro 'F2FS_GENERAL_RO_ATTR'
 1167 | static struct f2fs_attr f2fs_attr_##name = __ATTR(name, 0444, name##_show, NULL)
      |                         ^
<scratch space>:40:1: note: expanded from here
   40 | f2fs_attr_sec_fs_stat
      | ^
../fs/f2fs/sysfs.c:1375:2: error: use of undeclared identifier 'f2fs_attr_sec_defrag_stat'; did you mean 'f2fs_attr_sec_fs_stat'?
 1375 |         ATTR_LIST(sec_defrag_stat),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1321:27: note: expanded from macro 'ATTR_LIST'
 1321 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:23:1: note: expanded from here
   23 | f2fs_attr_sec_defrag_stat
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1246:1: note: 'f2fs_attr_sec_fs_stat' declared here
 1246 | F2FS_GENERAL_RO_ATTR(sec_fs_stat);
      | ^
../fs/f2fs/sysfs.c:1167:25: note: expanded from macro 'F2FS_GENERAL_RO_ATTR'
 1167 | static struct f2fs_attr f2fs_attr_##name = __ATTR(name, 0444, name##_show, NULL)
      |                         ^
<scratch space>:40:1: note: expanded from here
   40 | f2fs_attr_sec_fs_stat
      | ^
15 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: milxnaq <dupazlasu66@gmail.com>